from fastapi import Body,FastAPI, Path, Query, HTTPException
from pydantic import BaseModel, Field
from typing import Optional
from starlette import status

import books

app=FastAPI()

#this time we will be using a class to represent a book instead of a dictionary as in the previous example. This will allow us to have more control over the data and also make it easier to work with the data in the future when we want to add more functionality to our API. We can also use the class to create new books and add them to our list of books.
class Book:
    id:int
    title:str
    author:str
    description:str
    rating:float
    published_date:int

    def __init__(self, id, title, author, description, rating,published_date):
        self.id = id
        self.title = title
        self.author = author
        self.description = description
        self.rating = rating
        self.published_date = published_date #default value for published date, we can change it later when we want to add functionality to update the published date of a book

# class BookRequest(BaseModel): #pydantic base model to include data validation
#     id:int
#     title:str
#     author:str
#     description:str
#     rating:float

class BookRequest(BaseModel): #pydantic base model to include data validation
    id: Optional[int]=Field(description="Not needed", default=None) #id will be generated by the server, so it is optional in the request body
    title:str=Field(min_length=3) #adding field validation along with types
    author:str=Field(min_length=1)
    description:str=Field(min_length=1,max_length=100)
    rating:float=Field(ge= 0, le=5) #rating will be 1 to 5
    published_date:int=Field(ge= 0, le=2024) #published date will be between 0 and 2024

    #below thing is optional just to show example of defaults
    model_config = {
        "json_schema_extra": {
            "example": {
                "title": "The Great Gatsby",
                "author": "F. Scott Fitzgerald",
                "description": "A novel set in the Roaring Twenties, exploring themes of wealth, love, and the American Dream.",
                "rating": 4.5,
                "published_date": 2020
            }
        }
    }

books=[
    Book(1, "Title 1", "Author 1", "Description 1", 4.5, 2020),
    Book(2, "Title 2", "Author 2", "Description 2", 4.0,2001),
    Book(3, "Title 3", "Author 3", "Description 3", 3.5,2017),
    Book(4, "Title 4", "Author 4", "Description 4", 5.0,2015),
    Book(5, "Title 5", "Author 5", "Description 5", 4.2,2012),
    Book(6, "Title 6", "Author 6", "Description 6", 3.8,2012),
    Book(7, "Title 7", "Author 2", "Description 7", 4.1,2020),
        ]

@app.get("/books")
async def read_all_books():
    return books
@app.get("/books/{book_id}",status_code=status.HTTP_200_OK) #dynamic param should always eb after static ones
async def read_book(book_id: int = Path(gt=0)): #path parameter with validation, book id should be greater than 0
    for book in books:
        if (book.id) == book_id:
            return book
    #return {"message": "Book not found"}
    raise HTTPException(status_code=404, detail="Book not found") #raising an HTTP exception with status code 404 and a custom message when the book is not found

@app.get("/books/")
def read_book_by_rating(book_rating:int=Query(ge=0, le=5)): #query parameter with validation, book rating should be between 0 and 5
    books_to_return = []
    for book in books:
        if round(book.rating) == book_rating:
            books_to_return.append(book)
    return books_to_return

@app.get("/books/publish/")
def read_book_by_publish_year(published_date:int= Query(ge=0, le=2024)): #query parameter with validation, published date should be between 0 and 2024
    books_to_return = []
    for book in books:
        if book.published_date == published_date:
            books_to_return.append(book)
    return books_to_return

@app.post("/create_book",status_code=status.HTTP_201_CREATED)
def create_book(book_request: BookRequest): 
    # Unpacking the values of the book request and passing them to the book constructor
    new_book = Book(**book_request.dict()) 
    
    # Finding the id for the new book
    new_book = find_book_id(new_book) 
    
    # Adding it to the list of books
    books.append(new_book)
    return {"message": "Book created successfully", "book": new_book}


def find_book_id(book: Book):
    if len(books) == 0:
        book.id = 1
    else:
        # Find the highest ID currently in the list and add 1
        # (Assuming the 'books' list contains objects that have an 'id' attribute)
        book.id = max(existing_book.id for existing_book in books) + 1
        
    return book

@app.put("/books/update_book")
def update_book(book:BookRequest):
    for i in range(len(books)):
        if books[i].id == book.id:
            books[i] = Book(**book.dict()) #unpacking the values of the book request and passing them to the book constructor
            return {"message": "Book updated successfully", "book": books[i]}
    #return {"message": "Book not found"}
    raise HTTPException(status_code=404, detail="Book not found")

@app.delete("/books/remove_book/{book_id}")
def delete_book(book_id: int = Path(gt=0)):
    for i in range(len(books)):
        if books[i].id == book_id:
            # removing the book from the list and storing it in a variable
            deleted_book = books.pop(i) 
            return {"message": "Book deleted successfully", "book": deleted_book}
            
    # This only runs if the loop finishes entirely without finding a match
    return {"message": "Book not found"}
